# Generated by Django 5.2.7 on 2025-11-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_emailoperations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoperations',
            name='recipient',
            field=models.EmailField(max_length=254),
        ),
    ]
