# Generated by Django 5.2.7 on 2025-11-02 14:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_emailoperations_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoperations',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
